DROP TABLE IF EXISTS CONTRATOS;

CREATE TABLE CONTRATOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NIF VARCHAR(10),
    ADJUDICATARIO VARCHAR (200),
    OBJETO_GENERICO VARCHAR (200),
    OBJETO VARCHAR (200),
    FECHA_ADJUDICACION DATE,
    IMPORTE INT,
    PROVEEDORES_CONSULTADOS INT,
    TIPO_CONTRATO INT
);